### PR TITLE
PR: Do not include binaries in the tarball

### LINKED ISSUE #77: Why is the tarball so huge?
Shouldn't the tarball only include source files?  We currently include built files and it is 48MB.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #77

### CODE REVIEW

**Comment by andfoy** [comment]
Does removing the exe and dll references on the MANIFEST allows to add them to the binary wheels?

**Comment by blink1073** [comment]
I was reading up on that.  We may need to specifically add `package_data`.

**Comment by blink1073** [comment]
I haven't yet figured out how to exclude files from the sdist but not the wheel, will come back to this tomorrow.

**Comment by andfoy** [comment]
> I haven't yet figured out how to exclude files from the sdist but not the wheel, will come back to this tomorrow.

Thanks for the help on this

**Comment by blink1073** [comment]
Good to go now

**Pull request merged**
