### PR TITLE
PR: Add Python 2 support

### LINKED ISSUE #75: Python 2.7 Support?
Given @SylvainCorlay's comment [here](https://github.com/conda-forge/conda-forge.github.io/issues/460#issuecomment-343332639), I think we should resurrect https://github.com/spyder-ide/pywinpty/pull/66.  We are relying on `winpty` to handle the memory alloc/dealloc, and we are not passing OS primitives as described by @mingwandroid [here](https://github.com/conda-forge/conda-forge.github.io/issues/460#issuecomment-343320717).

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #75 

I used Microsoft Visual Studio 14.0 to build the Python 2.7 version.   See #75 for explanation.

### CODE REVIEW

**Comment by andfoy** [comment]
Well, the incompatibilities are related to the conda build system, i.e., To compile Py2.7 packages, MSVC 2010 is required. However, to compile winpty, 2013 version or later is requiered. Therefore, you cannot install on conda a package compiled with MSVC 2010 that depends on another package compiled on 2013 version. Unless we compile the packages manually ourselves, we cannot provide Python 2.7 supporr

**Comment by goanpeca** [comment]
@mingwandroid we need your wisdom.

**Comment by blink1073** [comment]
Why can't the build recipe effectively do what is done on appveyor to build it?

**Comment by blink1073** [comment]
i.e., use the precompiled winpty from conda forge.

**Comment by blink1073** [comment]
Then all you need to build is the cython wrapper.

**Comment by goanpeca** [comment]
WinPTY needs to be compiled with MSVC 2008 (not 2010, see [Python Docs](https://wiki.python.org/moin/WindowsCompilers)) for it to work with Py27 (but winPTY  needs 2013 or higher according to the [README](https://github.com/rprichard/winpty#embedding-winpty--msvc-compilation))

One can try to use PyWinpty with WinPTYcompiled with MSVC 2015 which is what is required for both Py35 and Py36 (see [Python Docs](https://wiki.python.org/moin/WindowsCompilers)) and it might look like it works... until it does not since they are not be binary compatible.

But @mingwandroid can explain all the intricacies of this much better than I can that is why I summoned him ;-)

**Comment by blink1073** [comment]
Ah, gotcha.

**Comment by ccordoba12** [comment]
Steve, the main problem is that Winpty requires a compiler with C++11 support:

https://github.com/rprichard/winpty#prerequisites

The first MSVC with full support for it is the 2013 one, so it can't be compiled for Python 2.7 using that toolchain.

The alternative is using MSYS2, which is the route modern C++ projects with Python bindings take to support Python 2.

I think that shouldn't be hard using conda: you just need to require the `posix` package, then you need to run the usual `configure && make`. Then you need to use MSYS2 to compile our Cython bindings too.

However, we don't have the resources to tackle this right now.

**Comment by blink1073** [comment]
Thanks for the pointers!

**Comment by blink1073** [comment]
I took a crack at it using the `winpty-feedstock` and tried both [mingwpy](https://github.com/mingwpy/mingwpy) and [m2w64-toolchain](https://anaconda.org/msys2/m2w64-toolchain) but quickly realized I was out of my depth.

**Comment by blink1073** [comment]
An update on this: I got most of the way there using the libs below, but we need `sys/select.h` and the libs that it includes, which are not natively available or provided by any of the `posix` or `m2*` packages as far as I can tell.

```
    - posix
    - m2-bash 
    - m2-make 
    - m2w64-toolchain
```

**Comment by blink1073** [comment]
I'm going to test this locally on Py2.7 against terminado.

**Comment by blink1073** [comment]
LGTM:

```bash
(py27) builder: /c/users/builder/workspace/terminado (winpty) 1
$ py.test
============================= test session starts =============================
platform win32 -- Python 2.7.14, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: C:\users\builder\workspace\terminado, inifile:
plugins: flaky-3.4.0
collected 8 items

terminado\tests\basic_test.py ........
===Flaky Test Report===


===End Flaky Test Report===

============================== warnings summary ===============================
terminado/tests/basic_test.py::TestTermClient
  cannot collect test class 'TestTermClient' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
==================== 8 passed, 1 warnings in 50.18 seconds ====================
```

```bash
builder: /c/users/builder/workspace/terminado (winpty) 1
$ py.test --pdb
============================= test session starts =============================
platform win32 -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: C:\users\builder\workspace\terminado, inifile:
plugins: flaky-3.4.0
collected 8 items

terminado\tests\basic_test.py ........
===Flaky Test Report===


===End Flaky Test Report===

============================== warnings summary ===============================
terminado/tests/basic_test.py::TestTermClient
  cannot collect test class 'TestTermClient' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
==================== 8 passed, 1 warnings in 56.55 seconds ====================
```

**Comment by goanpeca** [comment]
@blink1073 could you update the conda.recipe on conda-forge, then ?

**Comment by blink1073** [comment]
I was planning to use this approach that consumes the pre-built wheels: https://github.com/conda-forge/mingwpy-feedstock/blob/master/recipe/meta.yaml

**Comment by goanpeca** [comment]
@blink1073  why not use the normal approach and build the recipe, did  not you use msys2 at all?

---

I just don't want this to start failing in subtle ways...

**Comment by blink1073** [comment]
No, as I said above I ran into a brick wall with msys2 and a lack of appropriate header files.  I don't have a good example of building against `vc 14` with Python 2.7 and conda-forge, unless @SylvainCorlay can point me to one.

**Comment by blink1073** [comment]
Attempt in progress: https://github.com/conda-forge/pywinpty-feedstock/pull/7

**Comment by blink1073** [comment]
Okay, the build itself is succeeding there, we just need this release to pick up the handling of `backports.shutil_which`.

**Comment by blink1073** [comment]
cf https://ci.appveyor.com/project/conda-forge/pywinpty-feedstock/build/1.0.24/job/1eur4266240cym2c#L476

**Comment by ccordoba12** [comment]
Steve, I think you also need to remove the pin we added to Python 3 in 
the winpty feedstock. Or is that not necessary?

**Comment by blink1073** [comment]
I'm not entirely sure on that one, but worth doing to be sure.

**Comment by blink1073** [comment]
Ready when you are, @ccordoba12  :wink:

**Comment by ccordoba12** [comment]
I'd like @andfoy to take a last look at this one and merge it. I've barely been involved with this package.

@andfoy, I couldn't modify coveralls settings, so please do it yourself. You just need to change the minimum amount to report failures from 0% (the default) to 5% or something.

**Comment by blink1073** [comment]
Fair enough, I had to ask :smile:

**Comment by ccordoba12** [comment]
Jeje, no worries ;-)

**Comment by andfoy** [comment]
LGTM! Thanks for the great additions to pywinpty @blink1073 !

**Comment by blink1073** [comment]
More goodies coming pending `pexpect` integration!

**Comment by andfoy** [comment]
Merging then!

**Comment by blink1073** [comment]
:boom:

**Comment by andfoy** [comment]
@ccordoba12 I will give @blink1073 write permissions for this repo. Do you agree?

**Comment by ccordoba12** [comment]
Sure, please go ahead!

Steve, we finally managed to bring you back to work with us again ;-)

**Pull request merged**
