### PR TITLE
PR: Wait (blocking) for data when using PtyProcess

### PR DESCRIPTION
**Pull request by nanoant**
This is alternative solution to the problem described at https://github.com/jupyter/terminado/issues/54 and pull request workaround https://github.com/spyder-ide/pywinpty/pull/94.

Instead of doing any `time.sleep` `PtyProcess` read thread it is simply blocking waiting for `stdout` data. When the underlyiung console process dies, console pipe gets closed so read exits as well.

#### Notes

I have tested it with `pytest` and manually using JupyterLab console.

#### Commit notes

Previously PtyProcess thread was using non-blocking calls to read which
was effectively caused high-CPU usage, which was partially mitigated
by time.sleep(0.1).

NOTE: When console process dies the pipe gets closed, causing read to
return as well.

Also, removed superfluous `pty = pty_fixture()` calls from PtyProcess
that made tests hang with blocking approach on `cmd.exe`.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!  This change LGTM, but will need to wait for some build chain updates for CI to pass.  cf https://github.com/spyder-ide/pywinpty/pull/90#issuecomment-363934481

**Comment by nanoant** [comment]
@blink1073 @ccordoba12 Great! Thanks for the positive review. Cheers, Adam.

**Comment by scimax** [comment]
Thank you for your fix! The cpu usage improved a lot immediately! I copied the changes over manually although some checks were not successful. Before it was not possible to use the terminal over a long time.

**Comment by dhirschfeld** [comment]
What's the status of this PR? Is there anything I can do to help get this merged?

**Comment by ccordoba12** [comment]
We need to fix our testing infrastructure here, due to changes in how `winpty` is compiled in conda/conda-forge.

We hope to start working on it next week.

**Pull request merged**
