### PR TITLE
PR: [WIP] pexpect enhancements

### PR DESCRIPTION
**Pull request by blink1073**
- allow `read()` to be interrupted
- allow suppression of Cursor escape codes
- allow multiple entries in `LIBRARY_INC` and `LIBRARY_LIB`

### CODE REVIEW

**Comment by ccordoba12** [comment]
@blink1073, please define the milestone for this PR (v0.6?)

**Comment by blink1073** [comment]
Done!

**Comment by ccordoba12** [comment]
Thanks!

**Comment by ccordoba12** [comment]
Hey @blink1073, do you plan to finish this one?

**Comment by blink1073** [comment]
No, closing.

**Comment by ccordoba12** [comment]
@blink1073, could you describe what you were trying to achieve here so @andfoy can finish it? Thanks!

**Comment by blink1073** [comment]
This PR would have enabled a PR against `pexpect` based on this [branch](https://github.com/blink1073/pexpect/tree/winpty) that adds a `spawn` class for Windows that has the same API as the Unix `spawn`.  I was in the process of trying to get as many of the tests in `pexpect` to work as possible without disrupting the tests on Unix.

**Comment by goanpeca** [comment]
So can we close this then @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, let's close it.

**Pull request closed without merging**
