### PR TITLE
PR: Omit init file from coverage and fix Readme coverage badge

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfoy, please give me access to configure the settings for Pywinpty in `coveralls` so we can remove the reported failures in every drop in coverage.

**Comment by andfoy** [comment]
>  please give me access to configure the settings for Pywinpty in coveralls

@ccordoba12 How can I do this, I can't find any settings on coveralls

**Comment by ccordoba12** [comment]
I think you need to make me Admin of this repo.

**Comment by andfoy** [comment]
@ccordoba12 Done!

**Pull request merged**
