### PR TITLE
[WIP] Named pipe cleanup

### PR DESCRIPTION
**Pull request by blink1073**
Potential fix for #59.

### CODE REVIEW

**Comment by blink1073** [comment]
@SimonBiggs @dalito, do you mind trying out the snippet below with these changes?

You can make the changes by overwriting the `winpty_wrapper.py` file locally with the raw contents of the file in this PR, found in `python -c "import winpty; print(winpty.__path__[0])"`.

```python
from winpty import PtyProcess

proc = PtyProcess.spawn('python')
proc.write('print("hello, world!")\r\n')
proc.write('exit()\r\n')
while proc.isalive():
	print(proc.readline())
```

**Comment by SimonBiggs** [comment]
I won't get a chance till I'm back on my work computer on Monday. (It's Friday evening here now).

**Comment by SimonBiggs** [comment]
If it's not resolved by then though I shall give it a go :)

**Comment by SimonBiggs** [comment]
(All Linux at home)

**Comment by dalito** [comment]
I still get the same two errors (the order is random). Here is the result:
```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winpty import PtyProcess
>>> proc = PtyProcess.spawn('python')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\ptyprocess.py", line 113, in spawn
    inst = cls(proc)
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\ptyprocess.py", line 47, in __init__
    self._server.bind(address)
OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden
>>> proc = PtyProcess.spawn('python')
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\dev_amd64\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\dev_amd64\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\ptyprocess.py", line 337, in _read_in_thread
    data = pty.read(4096)
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\winpty_wrapper.py", line 86, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000
```
Do you have an idea why there are two different errors seen randomly? What can cause a timing problem?

Thanks for looking at this. I can continue to test possible fixes over the weekend.

**Comment by blink1073** [comment]
The port error is most likely due to an antivirus software or system policy limiting access to ports.   The default port is [20128](https://github.com/spyder-ide/pywinpty/blob/master/winpty/ptyprocess.py#L352).  Can you please try changing that line locally to default to `8888` (the one typically used by the Jupyter Notebook), to see if that clears it up?  We could allow for an environment variable to set the default port if it is an issue.  I'm still looking into the access violation...

**Comment by blink1073** [comment]
@dalito, I've updated the file in the PR with more debug info, and an attempt to read a second time if the first fails, can you please try that as well?

**Comment by dalito** [comment]
Here is the result
```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winpty import PtyProcess
>>> proc = PtyProcess.spawn('python')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\ptyprocess.py", line 113, in spawn
    inst = cls(proc)
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\ptyprocess.py", line 47, in __init__
    self._server.bind(address)
OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden
>>> proc = PtyProcess.spawn('python')
size 0
length 0
>>> conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 0
length 0
conout_pipe 392
size 8
length 8
conout_pipe 392
exception: access violation writing 0x0000000000000000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\winpty_wrapper.py", line 90, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev_amd64\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\dev_amd64\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\ptyprocess.py", line 337, in _read_in_thread
    data = pty.read(4096)
  File "C:\dev_src\_pyve\stable_py36\Lib\site-packages\winpty\winpty_wrapper.py", line 93, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000
```

**Comment by blink1073** [comment]
Unfortunately I am no closer to understanding what is going on here.

**Comment by SimonBiggs** [comment]
@blink1073 let me know if there is anything I can do. It might be possible to do a remote session if you wanted to do more hands on troubleshooting.

**Comment by SimonBiggs** [comment]
Just for reference here is me running the results of this pull request on my machine.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\sbiggs>python
Python 3.5.4 | packaged by conda-forge | (default, Aug 10 2017, 01:38:47) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winpty import PtyProcess
>>>
>>> proc = PtyProcess.spawn('python')
size 0
length 0
>>> conout_pipe 348
proc.write('print("hello, world!")\r\n')
size 0
length 0
conout_pipe 348
24
>>> size 0
proc.write('exit()\r\n')
length 0
conout_pipe 348
8
size 0
>>> length 0
while proc.isalive():
conout_pipe 348
size 0
... length 0
        print(proc.readline())conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 0
length 0
conout_pipe 348
size 8
length 8
conout_pipe 348
exception: access violation writing 0x0000000000000000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\site-packages\winpty\winpty_wrapper.py", line 88, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096)
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\site-packages\winpty\winpty_wrapper.py", line 91, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000
```

**Comment by SimonBiggs** [comment]
As an extra step our IT administrator temporarily disabled my antivirus.  This didn't stop the OSError from occuring.

**Comment by dalito** [comment]
To add to @SimonBiggs tests: Also when run as admin the error stays.

**Comment by ccordoba12** [comment]
@dalito, so this is not fixed by your PR?

**Comment by dalito** [comment]
I got two different errors randomly: This one and the "OSError: [WinError 10048]" which is fixed by #87. After applying #87 there will only be this error for me.

**Comment by andfoy** [comment]
AFAIK, this is a problem related to the Python distribution itself. The strange fact is that it should be resolved

**Comment by SimonBiggs** [comment]
My process of installing python was to install a recent Miniconda and then
run something like 'conda install python=3.5' to downgrade from 3.6 back to
3.5.

(Some of my dependencies were struggling with 3.6 on conda for some reason)

If you like I can uninstall Python and reinstall it with clear reproducible
steps to see if it is then reproducible on other machines.

**Comment by ccordoba12** [comment]
@SimonBiggs, could you see what happens in Python 3.6?

**Comment by SimonBiggs** [comment]
I did make a python 3.6 environment `conda create --name py36 python=3.6`
it still didn't work under that.

**Comment by ccordoba12** [comment]
@blink1073, what to do about this PR? Do you want to close or merge it?

**Comment by blink1073** [comment]
Closing, not sure what else to try here.

**Pull request closed without merging**
