### PR TITLE
PR: Fix for access violation error

### LINKED ISSUE #108: Access violation once again
I'm getting 

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Utilities\Development\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Utilities\Development\Python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Utilities\Development\Python\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread
    data = pty.read(4096, blocking=True)
  File "C:\Utilities\Development\Python\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x00000000

```
error whenever I'm trying to launch jupyter-notebook.

According to [this](https://stackoverflow.com/questions/14753939/unhandled-exception-at-0x76b1dd74-access-violation-writing-location-0x00000000) SO post the fourth parameter to ReadFile cannot be null.

Indeed, setting it to a valid pointer resolves the issue.

### PR DESCRIPTION
**Pull request by axil**
Fixes #108.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for this @axil! Are you able to start terminals in the Jupyter notebook with this change?

**Comment by axil** [comment]
Not sure what you mean by terminals in Jupyter. As for ipython kernels - yes, it starts them. But it did so without the patch as well. 

In the previous issue #59 with the similar symptoms they had troubles with terminal in spyder. I didn't check it out yet. Is it what you're asking about? 

I'm on Windows 7 64bit btw.

**Comment by blink1073** [comment]
I can confirm this change allows me to launch terminals from Jupyter on Windows 7, thanks @axil!

**Review by blink1073 — APPROVED** [review]

**Comment by ccordoba12** [comment]
Thanks @blink1073 for helping us to test that!

**Comment by axil** [comment]
Oh, ok. Got it. Looks like a new feature on Windows. Yes, works for me, too.

**Comment by wsvma** [comment]
Thanks for the fix! Sorry for a newbie question. I installed pywinpty via pip. When does a fix like this typically gets propagated so that the fix can be picked up via pip --upgrade?

**Comment by wsvma** [comment]
Nevermind my question. I figured it's just whenever next release (0.5.4) is made.

**Comment by axil** [comment]
@wsvma I see the following variants:
1) You can update the file manually, it works, but sort of considered bad practice. That's what I would do if I were you.
2) The developers can create a pre-release ending with something like "dev" to be installed with `pip install --pre`
3) You can wait for 0.5.4.

**Comment by ccordoba12** [comment]
We'll have other of couple simple issues to solve, then we'll release 0.5.4 (next week at most).

**Comment by wsvma** [comment]
Thanks @axil @ccordoba12

**Pull request merged**
