### PR TITLE
add support for arm64 compilation

### PR DESCRIPTION
**Pull request by niyas-sait**
This patch add support for compiling pywinpty for windows on arm64 targets.

### CODE REVIEW

**Comment by andfoy** [comment]
Thanks for this addition, unfortunately, we are not able to produce wheels on the CIs, since conda-forge does not have any python cross-compiler for arm64 on Windows, also the arm64 support on Maturin is still not on a release. Any help with this is highly appreciated

**Comment by niyas-sait** [comment]
@andfoy Yes it might take a bit to get conda-forge and CI support windows on arm64.

I think Maturin has a beta release on PyPI already.

We are expecting cloud availability on Azure soon so we could look into the release options but guess that doesn't have to block this as the people can build from at least source.

**Comment by andfoy** [comment]
@nsait-linaro, I take your word that it is working in arm64, thanks by the way

**Comment by niyas-sait** [comment]
Thanks @andfoy 👍

**Pull request merged**
